version: '3.7'

services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/fileConfig"
      - "--providers.file.watch=true"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--entryPoints.https.forwardedHeaders.trustedIPs="
      - "--entryPoints.https.proxyProtocol.trustedIPs="
      - "--certificatesResolvers.http.acme.email=[LE_EMAIL]"
      - "--certificatesResolvers.http.acme.storage=/acmestore/http.json"
      - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
      - "--certificatesresolvers.dns.acme.dnschallenge=true"
      - "--certificatesresolvers.dns.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.dns.acme.email=[LE_EMAIL]"
      - "--certificatesresolvers.dns.acme.storage=/acmestore/dns.json"
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acmestore:/acmestore
      - ./fileConfig:/fileConfig
    container_name: traefik
    environment:
      - CLOUDFLARE_EMAIL=[CF_EMAIL]
      - CLOUDFLARE_DNS_API_TOKEN=[CF_DNS_TOKEN]
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`[DOMAIN]`)"
      - "traefik.http.routers.traefik.middlewares=https-redirect@file"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`[DOMAIN]`)"
      - "traefik.http.routers.traefik-secure.middlewares=basic-auth@file"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=dns"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
